name: CI Backend

on:
  push:
    branches:
      - ci
env:
  DB_URI: ${{ secrets.DB_URI }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - run: npm ci
      - run: npm test